[platformio]
default_envs = pc

[env:pc]
platform = native
build_flags = -Wall -Wextra -lraylib -lGL -lm
build_src_filter = 
    -<*>
    +<*.c>
    +<hal/raylib/>
    +<modules/graphics/raylib/>
    +<modules/inputs/raylib/>

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git 
board = rpipico2
framework = arduino
upload_protocol = picotool
monitor_speed = 115200
board_build.core = earlephilhower 
build_flags = -Wall -Wextra -D PICO_STDIO_USB=1 -D PICO_STDIO_UART=0 -D SERIAL_USB -D DUSB_MMAP_SUPPORT
build_src_filter =
    -<*>
    +<*.c>
    +<hal/pico2/>
    +<modules/graphics/pico2/>
    +<modules/inputs/pico2/>
