[platformio]
default_envs = pc

[env:web]
platform = native
generator = unix
compiler = emcc
build_flags = -DPLATFORM_WEB -Os -Wall -Wextra -I/home/wilrakov/dev2026/vendored/emsdk/upstream/emscripten/system/include -I/home/wilrakov/dev2026/vendored/raylib/src /home/wilrakov/dev2026/vendored/raylib/src/libraylib.a -s USE_GLFW=3 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s FORCE_FILESYSTEM=1 -s ASYNCIFY
build_src_filter =
    -<*>
    +<*.c>
    +<hal/raylib/>
    +<modules/graphics/raylib/>
    +<modules/inputs/raylib/>
    +<modules/files/raylib/>
    +<modules/text/raylib/>
    +<modules/text/fonts/>
    +<modules/menu/>
    +<lua/>
    +<lua_modules/>


[env:pc]
platform = native
build_flags = -Wall -Wextra -lraylib -lGL -lm
build_src_filter =
    -<*>
    +<*.c>
    +<hal/raylib/>
    +<modules/graphics/raylib/>
    +<modules/inputs/raylib/>
    +<modules/files/raylib/>
    +<modules/text/raylib/>
    +<modules/text/fonts/>
    +<modules/menu/>
    +<lua/>
    +<lua_modules/>

[env:macos]
platform = native
build_flags =
    -Wall
    -Wextra
    -lraylib
    -Wl,-framework,OpenGL
    -Wl,-framework,Cocoa
    -Wl,-framework,IOKit
    -Wl,-framework,CoreVideo
    -Wl,-framework,AppKit
    -Wl,-framework,CoreFoundation
    -Wl,-framework,CoreGraphics
    -Wl,-framework,QuartzCore
build_src_filter =
    -<*>
    +<*.c>
    +<hal/raylib/>
    +<modules/graphics/raylib/>
    +<modules/inputs/raylib/>
    +<modules/files/raylib/>
    +<modules/text/raylib/>
    +<modules/text/fonts/>
    +<modules/menu/>
    +<lua/>
    +<lua_modules/>

[env:pico2-lcd1in3]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = picosdk
upload_protocol = picotool
monitor_speed = 115200
upload_flags = -f
build_flags = -Wall -Wextra -D PICO_STDIO_USB=1 -D PICO_STDIO_UART=0 -D SERIAL_USB -D DUSB_MMAP_SUPPORT
build_src_filter =
    -<*>
    +<*.c>
    +<hal/pico2/>
    +<modules/graphics/pico2-lcd1in3/>
    +<modules/inputs/pico2/>
    +<modules/files/pico2/>
    +<modules/text/pico2/>
    +<modules/text/fonts/>
    +<modules/menu/>
    +<lua/>
    +<lua_modules/>
